version: '2'
services:
    argos-app:
        image: argos
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://argos-mysql:3306/argos?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8085:8085
    argos-mysql:
        extends:
            file: mysql.yml
            service: argos-mysql
